### ISSUE TITLE
An easier way to manually edit the sidebar labels?

### ISSUE THREAD

**Issue by pbstFusion** [Nu-SCPTheme/Black-Highlighter#117]
**Is your feature request related to a problem? Please describe.**  
I'm always frustrated when I go on SCP Sandbox pages with BHL enabled. Not because BHL is bad or anything, but because BHL, in general, doesn't support large sidebar boxes. So whenever I go on there, it looks like the whole thing is broken because of the larger text used on SCP Sandbox 3 sidebox.

I have two potential solutions. Either add in a one-off sidebox change just for SCP Sandbox 3, or allow for more sidebar customisation.

Context:
![Screenshot 2021-11-06 154327](https://user-images.githubusercontent.com/64012878/140615415-a835ad12-932a-4b62-a3f3-ea3a0b029d93.png)

**Comment by SYwaves** [comment]
This is not caused by larger text on the sandbox - its because BHL is built to the specific structure of the wiki, where each row of item is wrapped in a menu-item div with set height, where as this only in one div but contain 5 links.

In general, fixing this would need a change on both sandbox divs and some of BHL's properties.

**Comment by Woedenaz** [comment]
SYwaves is correct. There is not a great way to fix this within BHL since I cannot specifically target the sandboxes via CSS code in the same way I can target INT branches.

This would primarily require a structural change for the sidebars on the Sandboxes and any other site that doesn't use the sidebar structure that BHL is expecting.
