### ISSUE TITLE
The line-through in links are invisible

### ISSUE THREAD

**Issue by hoah2333** [Nu-SCPTheme/Black-Highlighter#155]
**Describe the issue:**  If you put `--[[[link|123]]]--`, you can't see the strikethrough unless its be hovered. But the newpage links works fine.
Edit: Using `[[a href="link"]]--123--[[/a]]` is able to see the strikethrough, but it's not common to use.

**Screenshot showcasing the issue:**  ![line-through2](https://user-images.githubusercontent.com/17213700/200586256-2ef3760f-e385-4420-be45-15abe0d85032.gif)

**Link to the page(s) having this issue:**  http://scpdsandbox.wikidot.com/hoah2333

**Device information:** (fill in as appropriate)  
 - Device: PC
 - OS: Windows 11 Insider Preview 25236.1010
 - Browser: Google Chrome 107.0.5304.88

**Additional context:**  none

**Comment by Woedenaz** [comment]
Oh, strange! I'll look into fixing that right now. Thanks for the heads up!

**Comment by Woedenaz** [comment]
Noting that this seems to be an non-issue on Firefox but an even _worse_ issue on Safari (color me shocked.)

![Firefox on the left; Chrome in the middle; Safari on the right.](https://cdn.discordapp.com/attachments/458009355615207424/1055857206475628686/Screenshot_2022-12-23_at_9.37.54_AM.png)

It works just fine on Firefox. Functions as you described on Chrome. But on Safari, the newpage link also does not work.

Not sure what's causing it quite yet but I am not the least bit surprised that Safari is the worst performing browser here.

**Comment by Woedenaz** [comment]
I've narrowed down the issue. It's due to the line-through being on the <span> that wraps the link. BHL currently has the `text-decoration-color` on links set to `transparent` so that the underline on links fades in when hovered. 

However, line-through text decorations are also effected by this. On Firefox, it seems the line-through being set on the <span> overwrites the underline on the links. But on Safari and Chrome, the `text-decoration-color` set on the links cascades **upwards** for some godforsaken reason. So, despite the line-through being on the span, it's still set to transparent.

The fix for this is fortunately simple:

```css
[style*="line-through"] a,
[style*="line-through"] a:visited,
[style*="line-through"] a:active {
	text-decoration-color: inherit;
}
```

This seems to fix the problem. I'll be merging it into the primary branch soon.
