### ISSUE TITLE
Hovering texts doesn't disappear after removing the cursor (only on KO settings?)

### ISSUE THREAD

**Issue by XCninety** [Nu-SCPTheme/Black-Highlighter#234]
**Describe the issue:**  
Each time I put my cursor on the footnote number, the footnote box shows up correctly. When I remove the cursor, it doesn't fade away. I can't tell the exact date, but as far as I know this issue has been there for few months.

The known condition to reproduce this issue is:
- visit pages with Chromium browsers;
- only on Korean pages.

**Screenshot showcasing the issue:**  
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/56790522/81bfcf0b-35f7-46f4-acc8-7af207ed2c8f)

**Link to the page(s) having this issue:**  
http://scpko.wikidot.com/about-3333

**Device information:** (fill in as appropriate)  
 - Device: Irrelevant; both PC and Mobile
 - OS: Irrelevant; both WIndows and Android
 - Browser: Chromium browers; Chrome and Vivaldi for me (confirmed that Firefox doesn't reproduce this)
 - Version: Chrome 120.0.6099.110 / Vivaldi 6.5. 3206.39

**Additional context:**  
- Not mentioned above, but all of the hovering texts seem to make the same issue (i.e. buttons in the toolbox).
- There are also some pages without these issues, but I couldn't figure out why. (i.e. http://scpko.wikidot.com/scp-4991)

**Comment by hoah2333** [comment]
Maybe it's because of the [info component](http://scpko.wikidot.com/info:start), which may doesn't exactly same as [the English one](https://scp-wiki.wikidot.com/info:start). I can reproduce it by including a Black Highlighter theme from EN and a info component from KO. You can see the result from [my sandbox](http://scpdsandbox.wikidot.com/hoah2333) and the screenshot below.
![image](https://github.com/Nu-SCPTheme/Black-Highlighter/assets/17213700/93b6187a-97a7-4524-8f05-27334772edf5)

**Comment by XCninety** [comment]
Updated our info component (thanks to the teach team of our own), thanks!
