### ISSUE TITLE
Scrolling impossible with mobile firefox 

### ISSUE THREAD

**Issue by praecipitator** [Nu-SCPTheme/Black-Highlighter#45]
Example: http://www.scp-wiki.net/scp-4613
Open with a mobile firefox, or even a desktop firefox in a narrow window, and try to scroll.

The faulty rule is this one:
```
:root {
    scrollbar-width: none;
    overflow: -moz-scrollbars-none;
}
```
from https://nu-scptheme.github.io/Black-Highlighter/css/min/black-highlighter.min.css with the mediaquery @only screen and (max-width: 768px). That's all what I can get out of my browser.

I was able to make the site usable for myself by using an addon to add the rule `html {overflow:auto!important;}` to scp-wiki.net.

**Comment by Woedenaz** [comment]
I tried to reproduce this and I am not having the same issue. Do you know what version Firefox you are using?

**Comment by katzenpapst** [comment]
Yes, it works indeed with recent firefox. It is still reproducible with firefoxes <= about version 60, and with various forks, like Waterfox or Icecat. 

The reason is simple: the most recent firefox no longer supports -moz-scrollbars-none. This can be verified by opening the web developer tools and inspecting the <html> element.
