### ISSUE TITLE
Issue With the Italian SCP branch Layout

### ISSUE THREAD

**Issue by sebamarana** [Nu-SCPTheme/Black-Highlighter#54]
https://imgur.com/aRR5i5l

As seen in the imgur link we have a pair of problems with some of the side bar buttons.
It should be:
Sito
- SCP Casuale
- Cambiamenti Recenti

But instead is a broken mess.
Last note, i'd like the social links to be centered.

**Comment by Woedenaz** [comment]
I'll take a look at this asap! Sorry for the wait!

**Comment by Woedenaz** [comment]
Okay, I took a look. It appears that you are using nested side menu items which BHL isn't really fitted to deal with. I can see if I can add this functionality without also breaking the sidebar on other branches. I'll do my best but I can't promise that there will be a solution to this.

**Comment by Woedenaz** [comment]
Alright, looking this over, there's a few options here you could take.

Option 1 is the hackiest and it's adding a specific CSS class with an nth selector to the BHL import on your Theme page.

To fix the nested menu:
```css
div.menu-item:nth-child(15) {
  flex-wrap: wrap !important;
}
```

To fix the centered social icons:
```css
div.side-block {
    justify-content: center;
}
```

-----

The other option is to add specific CSS classes to those items and then I can add CSS styling to the main CSS of BHL. This would be the more evergreen option, especially if you ever end up editing your sidebar.

The social icons would also fix themselves if you changed the structure of them to

```
[[div class="side-block media" style="padding: 10px 0;"]]
[[=]]
[[image FB-icon.png link="https://www.facebook.com/FondazioneSCPitalia/?fref=ts"]] [[image Twitter-icon.png link="https://twitter.com/Fondazione_SCP" class="sns-icon"]] [[image Instagram-icon.png link="https://www.instagram.com/fondazione_scp_it_ufficiale/" class="sns-icon"]] [[image Discord-icon.png link="http://fondazionescp.wikidot.com/guida-alla-chat" class="sns-icon"]]
[[/=]]
[[/div]]
```
-----

I would also ask if that nesting is intentional or not? It wouldn't be an issue if the "Sito" header and the links below it weren't nested within the "Branche Internazionali" `.menu-item`

**Comment by Woedenaz** [comment]
This should be fixed with the newest version
