### ISSUE TITLE
Issue with top-bar on Russia SCP Branch.

### ISSUE THREAD

**Issue by MrNereof** [Nu-SCPTheme/Black-Highlighter#63]
Top bar dropdown doesn't open when I hover over them.

[Screenshot](http://scp-ru.wdfiles.com/local--files/draft%3Amrnereof/bhl.png)

**Comment by Woedenaz** [comment]
Hey there. I went and checked the them on your branch. Few things:

1. The dropdowns actually work for me, though they are not styled due to:
2. The structure of RU's top-bar appears to be... strange. [It is built on List Pages for some reason?](https://cdn.discordapp.com/attachments/571124195719905286/818517970602033172/Screen_Shot_2021-03-08_at_11.18.02_AM.png) BHL's code is not built to work with unusual top-bar structure like this so a RU patch will likely need to be made if it is kept this way.
3. I cannot even see RU's nav:top due to it being hidden.

Unfortunately, I do not personally have the time currently to make a specific RU branch patch. I certainly can _eventually_ but it might be a little while.
