### ISSUE TITLE
Problem about image-block.

### ISSUE THREAD

**Issue by bitterlord** [Nu-SCPTheme/Black-Highlighter#98]
Hello Woed. Me again.

I have started to have a problem ragarding the image-blocks in my theme. It looks like this.
![image](https://user-images.githubusercontent.com/88598402/129191128-841852f8-b596-4bfb-b406-46bc36063114.png)
Well, how can I solve this? Thanks in advance.

**Comment by Woedenaz** [comment]
Hey there. It'd be helpful if you could give me the page where this is happening :]

If this is similar to other image reports we have seen using the scp-image-block component, and you want this to be a full width image, then you need to set the width to `100%`. If you leave the `|width=` blank, it will default to 300px. If you put something like `|width=300` it will, instead, default to the maximum width of image up to the width of the container block (likely #main-content)

To be clear, this is not an issue with BHL and likely an issue with some sort of missing or invalid width value. It likely worked before on old BHL due to old BHL sort of "correcting" these errors. This code was removed to fix another issue it caused, so now widths need to be set for these blocks.

**Comment by bitterlord** [comment]
http://selimtan.wikidot.com/testullah

Here is the page. I will try making what you said and give you information about the result.

**Comment by bitterlord** [comment]
Yes, not enough hawing the alignment problem but...
![image](https://user-images.githubusercontent.com/88598402/129428641-2bc4f2d2-96b0-4ed5-b697-9791d6b26a26.png)
This now.

And even how I edit the "|width=XXX" part, nothing changes. Like, when I took the SS it was 20 and it was same as 10, 100, 300 and 500.

**Comment by Woedenaz** [comment]
You need to add a unit or it will not work. px/em/rem or vw/vmax/%

**Comment by bitterlord** [comment]
I can change the size of it but the gap is still there.

**Comment by Woedenaz** [comment]
Ah okay, I misunderstood your issue.

So, looking at the source, this is the `.image-block` instead of the `.scp-image-block`. Seems the plain `.image-block` was missing some styling so I just pushed a fix for that. It should be live soon.

**Comment by bitterlord** [comment]
Nothing for now, I will re-inform you when I take a look on it again

**Comment by Woedenaz** [comment]
I switched the theme import to jsdelivr so it may take a little while to update now.

**Comment by bitterlord** [comment]
Nothing happened in this 20 minutes.

**Comment by bitterlord** [comment]
11 hours after, still the same.

**Comment by Woedenaz** [comment]
This appears to be fixed now.
